---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	cluster_dedupe(cluster_dedupe)
	score(score)
	scrape_blogs(scrape_blogs)
	process_adhoc_input(process_adhoc_input)
	__end__([<p>__end__</p>]):::last
	__start__ -.-> process_adhoc_input;
	__start__ -.-> scrape_blogs;
	cluster_dedupe --> score;
	process_adhoc_input --> cluster_dedupe;
	scrape_blogs --> cluster_dedupe;
	score --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
