---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ingest_bookmarks(ingest_bookmarks)
	cluster_dedupe(cluster_dedupe)
	score(score)
	__end__([<p>__end__</p>]):::last
	__start__ --> ingest_bookmarks;
	cluster_dedupe --> score;
	ingest_bookmarks --> cluster_dedupe;
	score --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
